name: Update Bitcoin Price

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes
  workflow_dispatch:        # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Fetch and Update Bitcoin Price
        run: python fetch_price.py

      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add index.html
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m "Update Bitcoin price [skip ci]"
            git push origin HEAD:${{ github.ref }} --force
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Fetch and Update Bitcoin Price
        run: |
            python fetch_price.py || exit 1

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          
